const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const root=path.resolve(__dirname,'..'),repo=path.resolve(root,'../..');
const schema=require('./api-schema.cjs');
const dir=path.join(repo,'Assets/Scripts/Eclipse/Modding');
const sources=fs.readdirSync(dir).filter(n=>/^MoonSharpScriptRuntime.*\.cs$/.test(n)).map(n=>fs.readFileSync(path.join(dir,n),'utf8'));
const tables=new Map();
for(const s of sources) for(const [,name,variable] of s.matchAll(/root\.Set\("(\w+)"\s*,\s*DynValue\.NewTable\((\w+)\)/g)) tables.set(variable,[name]);
for(const s of sources) for(const [,list] of s.matchAll(/foreach\s*\(string name in new\[\]\s*\{([^}]+)\}/g)) tables.set('module',[...list.matchAll(/"(\w+)"/g)].map(m=>m[1]));
tables.set('projectileTable',['projectile']);tables.set('actorTable',['actor']);
tables.set('fighterTable',['fighter']);tables.set('targetTable',['fighter.opponent']);
const exported=new Set(['require']),constants={};
for(const s of sources){
    for(const [,v,n] of s.matchAll(/(\w+)\.Set\("(\w+)"\s*,\s*DynValue\.NewCallback\(/g)){
        if(v==='Globals'&&n==='require'||v==='Table')continue;
        assert(tables.has(v),`Unmapped runtime table ${v}.${n}`);
        for(const t of tables.get(v))exported.add((t.startsWith('fighter')||['projectile','actor'].includes(t))?`${t}:${n}`:`sf2.${t}.${n}`);
    }
    for(const [,m,n] of s.matchAll(/root\.Get\("(\w+)"\)\.Table\.Set\("(\w+)"\s*,\s*DynValue\.NewCallback\(/g))exported.add(`sf2.${m}.${n}`);
    for(const [,v,n] of s.matchAll(/(\w+)\.Set\("(\w+)"\s*,\s*\w+\.Get\("\w+"\)\)/g)) for(const m of tables.get(v)??[])exported.add(`sf2.${m}.${n}`);
    for(const [,n] of s.matchAll(/\{\s*"(on_\w+)"\s*,\s*ModEffectEvent\./g))exported.add(n);
    for(const [,v,n,value] of s.matchAll(/(\w+)\.Set\("([A-Z][A-Z_0-9]*)"\s*,\s*DynValue\.NewString\("([^"]*)"\)/g))for(const m of tables.get(v)??[])constants[`sf2.${m}.${n}`]=value;
}
if(sources.some(s=>/table\.Get\("on_result"\)/.test(s)))exported.add('on_result');
for(const name of ['on_click','on_close','on_change','on_back','on_decide','on_prepare'])if(sources.some(s=>s.includes(`table.Get("${name}")`)))exported.add(name);
if (sources.some(source => source.includes('definition.Get("on_complete")'))) exported.add('on_complete');
if (sources.some(source => source.includes('definition.Get("on_cancel")'))) exported.add('on_cancel');
if (sources.some(source => source.includes('":on_before_fight"'))) exported.add('on_before_fight');
const covered=new Set([...Object.keys(schema.actorMethods).map(n=>'actor:'+n),...Object.keys(schema.projectileMethods).map(n=>'projectile:'+n),'require',...Object.keys(schema.functions),...Object.keys(schema.aliases),...schema.callbacks,...schema.storyCallbacks,...schema.modeCallbacks,...schema.uiCallbacks,...schema.aiCallbacks,...Object.keys(schema.fighterMethods).map(n=>'fighter:'+n),'fighter.opponent:change_health','fighter.opponent:add_magic_charge','fighter.opponent:move_by','fighter.opponent:play_move','fighter.opponent:overlaps_rect']);
assert.deepEqual([...covered].sort(),[...exported].sort(),'LuaLS schema must cover every runtime function, alias and callback exactly.');
const docs={};
for(const file of fs.readdirSync(path.join(repo,'Docs/Modding/src/content/docs/api'))){
    if(!file.endsWith('.md'))continue;
    const text=fs.readFileSync(path.join(repo,'Docs/Modding/src/content/docs/api',file),'utf8');
    for(const match of text.matchAll(/^## (.+)\r?\n([\s\S]*?)(?=^## |$(?![\s\S]))/gm)){
        const name=match[1].trim();if(!exported.has(name))continue;
        const body=match[2].trim();
        const label=n=>body.match(new RegExp(`\\*\\*${n}:\\*\\* ([\\s\\S]*?)(?:\\r?\\n\\r?\\n|$)`))?.[1].replace(/\s+/g,' ').trim()??'';
        docs[name]={url:`https://dawc17.github.io/ProjectEclipse/api/${file.slice(0,-3)}/#${name.replace(/[.:]/g,'')}`,summary:body.split(/\r?\n\r?\n/)[0].startsWith('**')?'':body.split(/\r?\n\r?\n/)[0].replace(/\s+/g,' '),requires:label('Requires'),when:label('When'),returns:label('Returns')};
    }
}
for(const name of covered) assert(docs[name]||name==='require',`Missing public documentation for ${name}`);
let out='---@meta sf2\n\n-- Generated by scripts/generate.cjs from the authored schema and current public wiki.\n-- Editor-only metadata. Never load these declarations in Eclipse.\n\n';
for(const [name,{fields,parent}] of Object.entries(schema.types)){
    out+=`---@class (exact) Eclipse.${name}${parent?': Eclipse.'+parent:''}\n`;
    for(const [key,value] of Object.entries(fields)){const [type,doc]=Array.isArray(value)?value:[value,''];out+=`---@field ${key} ${type}${doc?' '+doc:''}\n`;}
    out+=`local ${name} = {}\n\n`;
}
const modules=[...new Set([...Object.keys(schema.functions),...Object.keys(schema.aliases),...Object.keys(constants)].map(n=>n.split('.')[1]).concat('mod'))].sort();
for(const m of modules){out+=`---@class Eclipse.Module_${m}\n`;if(m==='mod')for(const n of ['id','name','version'])out+=`---@field ${n} string\n`;out+=`local ${m} = {}\n\n`;}
function comment(name){const d=docs[name];return [d.summary,`Requires: ${d.requires}`,`When: ${d.when}`,`Returns: ${d.returns}`,`[Full reference](${d.url})`].filter(Boolean).map(s=>'---'+s).join('\n')+'\n';}
for(const [name,f] of Object.entries(schema.functions)){
    out+=comment(name);
    if(f.overload)out+=`---@overload ${f.overload}\n`;
    for(const [p,t] of Object.entries(f.params))out+=`---@param ${p} ${t}\n`;
    if(f.returns!=='nil')out+=`---@return ${f.returns}\n`;
    out+=`function ${name.slice(4)}(${Object.keys(f.params).map(n=>n.replace(/\?$/,'')).join(', ')}) end\n\n`;
}
for(const [name,target] of Object.entries(schema.aliases)) out+=comment(name)+`${name.slice(4)} = ${target.slice(4)}\n\n`;
for(const [name,value] of Object.entries(constants))out+=`---@type ${JSON.stringify(value)}\n${name.slice(4)} = ${JSON.stringify(value)}\n\n`;
for(const [name,f] of Object.entries(schema.fighterMethods))for(const opponent of [false,...(['change_health','add_magic_charge','move_by','play_move','overlaps_rect'].includes(name)?[true]:[])]){
    const symbol=`fighter${opponent?'.opponent':''}:${name}`;
    out+=comment(symbol);
    for(const [p,t] of Object.entries(f.params))out+=`---@param ${p} ${t}\n`;
    if(f.returns)out+=`---@return ${f.returns}\n`;
    out+=`function ${opponent?'Opponent':name==='scale_incoming_damage'?'ResolvingFighter':['scale_outgoing_damage','add_outgoing_damage'].includes(name)?'OutgoingFighter':'Fighter'}:${name}(${Object.keys(f.params).join(', ')}) end\n\n`;
}
for(const [name,f] of Object.entries(schema.projectileMethods)){
    out+=comment('projectile:'+name);
    for(const [p,t] of Object.entries(f.params))out+=`---@param ${p} ${t}\n`;
    out+=`---@return ${f.returns}\nfunction Projectile:${name}(${Object.keys(f.params).join(', ')}) end\n\n`;
}
for(const [name,f] of Object.entries(schema.actorMethods)){
    out+=comment('actor:'+name);
    for(const [p,t] of Object.entries(f.params))out+=`---@param ${p} ${t}\n`;
    out+=`---@return ${f.returns}\nfunction Actor:${name}(${Object.keys(f.params).join(', ')}) end\n\n`;
}
out+=`return { ${modules.map(m=>`${m} = ${m}`).join(', ')} }\n`;
const metadata={functions:Object.fromEntries(Object.entries(schema.functions).map(([n,f])=>[n,{...f,...docs[n]}])),aliases:schema.aliases,constants,callbacks:schema.callbacks,storyCallbacks:schema.storyCallbacks,modeCallbacks:schema.modeCallbacks,uiCallbacks:schema.uiCallbacks,aiCallbacks:schema.aiCallbacks,fighterMethods:schema.fighterMethods,projectileMethods:schema.projectileMethods,actorMethods:schema.actorMethods,types:schema.types};
fs.mkdirSync(path.join(root,'data'),{recursive:true});
for(const [file,content] of [['library/sf2.d.lua',out],['data/api.json',JSON.stringify(metadata,null,2)+'\n']]){
    if(process.argv.includes('--check'))assert.equal(fs.readFileSync(path.join(root,file),'utf8').replace(/\r\n/g,'\n'),content,`${file} is stale; run npm run generate`);
    else fs.writeFileSync(path.join(root,file),content);
}
console.log(`Verified ${exported.size} public functions/aliases/callbacks and ${Object.keys(constants).length} constants; ${Object.keys(schema.types).length} typed structures.`);
